### ISSUE TITLE
Host and port issue for FAQs

### ISSUE THREAD

**Issue by robin-thompson** [jstockwin/EpiEstimApp#130]
From Rolina email:

I got it to work on my work computer. The problem was that I had to specify an available host and port. 
EpiEstimApp::runEpiEstimApp(port=1410, host="127.0.0.1") 

Links on https://github.com/rstudio/httpuv/issues/34 provide a way to try random ports until an available one is found. Perhaps an idea for the app? 

Rolina

**Comment by jstockwin** [comment]
This is as simple as removing the `port=3000` override and instead using Shiny's default behaviour (which does the port scanning thing as mentioned above). If we do this, we need to remember to add a `port=3000` override when starting the app for tests.
