### ISSUE TITLE
EpiEstim App fail to save Image

### ISSUE THREAD

**Issue by applebear0507** [jstockwin/EpiEstimApp#190]
when I run EpiEstimApp()
I want to save Image of the result.
However,when  I  click the "Save Image", I cannot save Image.
Thank you !

**Comment by jstockwin** [comment]
Hey @applebear0507. Thanks submitting the issue. I've reproduced the problem, and submitted a fix in #191.

It'll take a while for tests to finish, but I'll try and get this merged ASAP.

If you're using the app locally, you should be able to switch to the new version already by running `devtools::install_github("jstockwin/EpiEstimApp", ref="fix-plot-download", force = TRUE)`.

If you're using the hosted version at https://shiny.dide.imperial.ac.uk/epiestim/, I'll try and get them to update this as soon as possible and let you know when it's done.

**Comment by jstockwin** [comment]
The fix has now been merged, and released in version `1.0.1`. I'll give a further update when the hosted version is updated.

**Comment by applebear0507** [comment]
That is wonderful!
 I appreciate it very much.
It is convenient to evaluate R(t) of Corona Virus Disease 2019 (COVID-19)  by using  EpiEstim App.
WELL DONE! Thank you again!
| |
wpjia301
|
|
18519196066@163.com
|
签名由网易邮箱大师定制
On 2/25/2020 18:42，Jake Stockwin<notifications@github.com> wrote：

The fix has now been merged, and released in version 1.0.1. I'll give a further update when the hosted version is updated.

**Comment by robin-thompson** [comment]
No problem at all - I'm glad that Jake could help!  

When using the App, we would be really grateful if you could please cite our paper on EpiEstim 2:
Thompson RN, Stockwin JE, van Gaalen RD, Polonsky JA, Kamvar ZN, Demarsh PA, Dahlqwist E, Li S, Miguel E, Jombart T, Lessler J, Cauchemez S, Cori A. Improved inference of time-varying reproduction numbers during infectious disease outbreaks (2019) Epidemics, 29:100356

Thank you! And we are pleased you enjoyed using the App!

**Comment by jstockwin** [comment]
This fix has now been merged into release and deployed to https://shiny.dide.imperial.ac.uk/epiestim/
