### ISSUE TITLE
Incidence data table is incorrect

### ISSUE THREAD

**Issue by jstockwin** [jstockwin/EpiEstimApp#69]
Currently, the incidence data table shows the imported cases + local cases, rather than having a column for each. This is EpiEstim being consistent with old behaviour patterns (ref: [issue](https://github.com/annecori/EpiEstim/issues/18)), and so we need to account for this in the app.

**Comment by annecori** [comment]
I quite like option 1 because it clarifies the underlying assumption made, i.e. if people don't specify which cases are imported the ones on the first time step are assumed to be imported.

**Comment by jstockwin** [comment]
Fine by me, that makes things easier.
