### ISSUE TITLE
Seeds for preloaded data

### ISSUE THREAD

**Issue by jstockwin** [jstockwin/EpiEstimApp#80]
When using pre-loaded data, the data is saved AFTER the MCMC run, so setting the seed will not change this. 

There are basically two options: 
- have a big warning explaining that this is what happens
- save MCMC output for say 10 different seeds
- run MCMC even when using preloaded data

@annecori and @jstockwin think the first option and @robin-thompson things the second might be better. We need to work out what to do about this. 

We could potentially ask the question specifically ("do you want to choose MCMC params etc yourself, or just use our pre-run MCMC output?"). This might be a bit of a pain to code, though.

**Comment by robin-thompson** [comment]
Agree with this, although what I actually favour is a hybrid of the 2nd and 3rd options:

Save MCMC output for 10 different seeds (1...10, say). Pick randomly out of these if the seed is not specified.  If the seed is specified, and is between 1 and 10, then use the relevant preloaded data.  If the seed is specified and is not between 1 and 10, then run the MCMC.

The key question we have to decide is what we think the preloaded data is for.  In my opinion, it is to demonstrate how the app would work in a real outbreak response scenario, when the user uploads their own data. Consequently I think having some randomness in SI estimates is important, even for the preloaded data. And therefore the way I describe above is a neat way of achieving this, I think...

**Comment by jstockwin** [comment]
I would have said the pre-loaded data is a quick way to see some example output, in the case that you don't really care about advanced inputs (such as the seed). If you care about changing the inputs then you should be uploading the datasets yourself. These can still be the same as the pre-loaded dataset, you just have to grab them from the file structure.

**Comment by robin-thompson** [comment]
Ok then, how about this solution?  Move the advanced options to appear only at the stage where you upload your own SI data.  That way the user can't falsely think they are changing the seeds when using preloaded data - and no warning is necessary either.

**Comment by jstockwin** [comment]
But the seeds are for more than just the MCMC stuff?

@annecori said on slack:  "note there is randomness in other places though
when we use numerical sampling from the posterior, e.g. for UncertaintySI
method"

**Comment by robin-thompson** [comment]
Ok, and does each method only use at most 1 seed? (we don't want to seed exactly the same set of random numbers at the beginning of the MCMC and when you sample out of the posterior...)?  

I would still favour getting the user to choose seeds only at the points in the overall method where the seeds actually apply...  Thereby removing the need for a warning (in the case where you are proposing to ignore the seed) and making precisely what the seed is in each case much clearer...

**Comment by robin-thompson** [comment]
Ultimately, though, since you understand the method and have put together a great app, it's up to you.  I'm just suggesting what I think would make the most sense for the user.  But if you disagree, feel free to ignore.

**Comment by annecori** [comment]
Haven't read in detail your discussion, but in short, I think options to fix the seed should be applied where needed, i.e. 1) just before running the MCMC IF running the MCMC (i.e. not with preloaded SI posteriors) and 2) for the numerical sampling i.e. for methods UncertaintySI and SIFromSamples. This could be pre-filled with a default value that the user can then change if desired?

**Comment by jstockwin** [comment]
Alright, I'm happy to do this. Are we sure these are the only places where a seed is used:
- When running MCMC (passed to `dic.fit.mcmc`)
- When running UncertainSI
- When running SIFromSamples

I'm confused by the SIFromSamples one - this is the one run on the output of MCMC. If this is random then surely there are also two random parts to SIFromData, the MCMC bit and the sampling bit?

Also @annecori exactly where are the prior parameters used?


I still don't really see the need for separate seeds all over the place. If you pick a seed, the results should be reproducible, otherwise they won't be. In the case of pre-loaded data we warn that you're losing randomness and point to instructions on how to overcome this (by uploading the file yourself). 


I also don't think I agree with having a default seed. Surely the default behaviour is to use a random seed. The naive user may run the app server times (without looking at the advanced options) to see how much the estimates change, and if we're setting a default seed then they won't change?

**Comment by annecori** [comment]
yes you are right sorry, also need this for SIFRomData

**Comment by annecori** [comment]
happy with not having a default seed

**Comment by annecori** [comment]
not sure what do you mean by where are the prior used; they are used for ALL methods, so I think should be fixed at the same time as you fix the time window

**Comment by annecori** [comment]
for the seed, there are 2 sources of stochasticity, one specific to the MCMC and the other due to numerical sampling from the posterior distribution of R; these 2 are independent and so that's why I think it's good to be able to change each of these separately
for instance, if you choose a smallish n1 (or n2 can never remember) you may want to check whether this is large enough for your results to be stable if you rerun with a different seed - this is completely independent from the MCMC so requires a separate seed (because you may want to use the SAME MCMC results BUT different sampling afterwards). Does that make sense?

**Comment by jstockwin** [comment]
@annecori Your last point makes sense, yes. 
I'll move the prior parameters to where the width is set, then, and add some seeds in various places. 

I think given we're now adding just one or two options, I might do away with the whole "advanced options" thing and just add them as normal inputs.

**Comment by jstockwin** [comment]
**Plan:**
- [ ] Remove the current "advanced options" bit from state 1.1. 
- [ ] Also remove the "show advanced options" and corresponding JS
- [ ] Add `uploadedMeanPrior` and `uploadedStdPrior` to state 2.1
- [ ] Add `incidenceMeanPrior` and `incidenceStdPrior` to state 2.2
- [ ] Add `UploadedSISeed` to state 8.2
- [ ] Add `MCMCSeed` to state 9.1
- [ ] Add `SISampleSeed` to state 8.3
- [ ] Add `uncertainSeed` to state 7.3

Then, whichever route is taken through the decision tree, you are asked to provide prior parameters when you choose the width. Seed parameters are only requested for those routes which involve randomness. In particular, no seed is requested when using pre-loaded data, or when running any type of `ParametricSI` or `NonParametricSI`. 

@annecori If you see this before tomorrow (Sunday) can you check it looks reasonable, as I'll be implementing it then. If not, you can check after I've done it and hopefully I've not gone too far wrong!
