### ISSUE TITLE
window width is wrong

### ISSUE THREAD

**Issue by annecori** [jstockwin/EpiEstimApp#83]
- [ ] I think at the moment the window width is wrong, i.e. when one chooses 7 days as the window, the actual window used is 8 days

- [ ] Also, the estimation can only ever start at time step 2 after the first incident case; so for a weekly window the first interval to consider should be T.Start = 2 and T.End = 8

**Comment by jstockwin** [comment]
Thanks, @annecori. 

Additional info as follows:

Relevant code is
https://github.com/jstockwin/EpiEstimApp/blob/master/inst/app/server.R#L337
and
https://github.com/jstockwin/EpiEstimApp/blob/master/inst/app/server.R#L354

From what you're saying, both of these *should* read
```
               T.Start <<- 2:(length - W +1)
               T.End <<- (1+W):length
```
for `length=10` and `W=7` this gives `T.Start = 2:4` and `T.End=8:10`. This is in contrast to the *current (wrong)* code:
```
               T.Start <<- 1:(length - W)
               T.End <<- (1+W):length
```
which for `length=10` and `W=7` this gives the incorrect `T.Start = 1:3` and `T.End=8:10`.

Do you agree with that? Will make a PR in the web interface quickly if so. 


Side note: I assume we're happy that the app doesn't give the full choice that EpiEstim does of having different window widths? I think this would be quite hard to code, we'd maybe need to have another file upload to deal with it....

**Comment by jstockwin** [comment]
@annecori Have made the above changes in PR #84, which I've requested a review from you on. 
Note I've **NOT** checked it at all, so please test!
